/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pages;

import dao.BorcDao;
import dao.BorcDetayDao;
import dao.KullaniciDao;
import dao.SicilDao;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Insets;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import model.Borc;
import model.BorcDetay;
import model.Kullanici;
import model.Sicil;

/**
 *
 * @author ahmedsalihh
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        initFrameStyles();

        sicilGosterPane.setVisible(false);
        tumBorclarPane.setVisible(false);
        sicilEkle.setVisible(false);
        kullaniciYonetimiPane.setVisible(false);

    }

    public void initFrameStyles() {

        btnSicilGoster.setBackground(new Color(59, 89, 182));
        btnSicilGoster.setForeground(Color.WHITE);
        btnSicilGoster.setFocusPainted(false);
        btnSicilGoster.setFont(new Font("Tahoma", Font.BOLD, 12));
        btnSicilGoster.setBorderPainted(false);

        btnSicilEkle.setBackground(new Color(59, 89, 182));
        btnSicilEkle.setForeground(Color.WHITE);
        btnSicilEkle.setFocusPainted(false);
        btnSicilEkle.setFont(new Font("Tahoma", Font.BOLD, 12));
        btnSicilEkle.setBorderPainted(false);

        btnTumBorclar.setBackground(new Color(59, 89, 182));
        btnTumBorclar.setForeground(Color.WHITE);
        btnTumBorclar.setFocusPainted(false);
        btnTumBorclar.setFont(new Font("Tahoma", Font.BOLD, 12));
        btnTumBorclar.setBorderPainted(false);

        btnKullaniciYonetimi.setBackground(new Color(59, 89, 182));
        btnKullaniciYonetimi.setForeground(Color.WHITE);
        btnKullaniciYonetimi.setFocusPainted(false);
        btnKullaniciYonetimi.setFont(new Font("Tahoma", Font.BOLD, 12));
        btnKullaniciYonetimi.setBorderPainted(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPane = new javax.swing.JPanel();
        btnSicilGoster = new javax.swing.JButton();
        btnSicilEkle = new javax.swing.JButton();
        btnTumBorclar = new javax.swing.JButton();
        btnKullaniciYonetimi = new javax.swing.JButton();
        sicilGosterPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSicil = new javax.swing.JTable();
        btnKrediEkle = new javax.swing.JButton();
        btnSicilSil = new javax.swing.JButton();
        btnSicilDuzenle = new javax.swing.JButton();
        sicilEkle = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTCNO = new javax.swing.JTextField();
        txtAd = new javax.swing.JTextField();
        txtSoyad = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        txtAdres = new javax.swing.JTextField();
        btnSicilEkle1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAciklama = new javax.swing.JTextField();
        tumBorclarPane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTumBorclar = new javax.swing.JTable();
        kullaniciYonetimiPane = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtKullaniciAdi = new javax.swing.JTextField();
        txtSifre = new javax.swing.JTextField();
        txtKullaniciAd = new javax.swing.JTextField();
        txtKullaniciSoyad = new javax.swing.JTextField();
        txtTelNo = new javax.swing.JTextField();
        btnSicilEkle2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setSize(new java.awt.Dimension(1024, 768));

        menuPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSicilGoster.setText("Sicil Goster");
        btnSicilGoster.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSicilGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSicilGosterActionPerformed(evt);
            }
        });

        btnSicilEkle.setText("Sicil Ekle");
        btnSicilEkle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSicilEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSicilEkleActionPerformed(evt);
            }
        });

        btnTumBorclar.setText("Tum Borclar");
        btnTumBorclar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTumBorclar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTumBorclarActionPerformed(evt);
            }
        });

        btnKullaniciYonetimi.setText("Kullanici Yonetimi");
        btnKullaniciYonetimi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKullaniciYonetimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullaniciYonetimiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPaneLayout = new javax.swing.GroupLayout(menuPane);
        menuPane.setLayout(menuPaneLayout);
        menuPaneLayout.setHorizontalGroup(
            menuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSicilGoster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSicilEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTumBorclar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnKullaniciYonetimi, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
        );
        menuPaneLayout.setVerticalGroup(
            menuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPaneLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(btnSicilGoster, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSicilEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTumBorclar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKullaniciYonetimi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        sicilGosterPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblSicil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblSicil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSicil);

        btnKrediEkle.setText("Kredi Ekle");
        btnKrediEkle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKrediEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKrediEkleActionPerformed(evt);
            }
        });

        btnSicilSil.setText("Sicil Sil");
        btnSicilSil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSicilSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSicilSilActionPerformed(evt);
            }
        });

        btnSicilDuzenle.setText("Sicil Duzenle");
        btnSicilDuzenle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSicilDuzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSicilDuzenleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sicilGosterPaneLayout = new javax.swing.GroupLayout(sicilGosterPane);
        sicilGosterPane.setLayout(sicilGosterPaneLayout);
        sicilGosterPaneLayout.setHorizontalGroup(
            sicilGosterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sicilGosterPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sicilGosterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKrediEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSicilSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSicilDuzenle, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addContainerGap())
        );
        sicilGosterPaneLayout.setVerticalGroup(
            sicilGosterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sicilGosterPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(sicilGosterPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnKrediEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSicilSil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSicilDuzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sicilEkle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Soyad");

        jLabel4.setText("Telefon");

        jLabel5.setText("Adres");

        txtTCNO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtAd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtSoyad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTelefon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtAdres.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSicilEkle1.setText("Ekle");
        btnSicilEkle1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSicilEkle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSicilEkle1ActionPerformed(evt);
            }
        });

        jLabel1.setText("TCNO");

        jLabel2.setText("Ad");

        jLabel6.setText("Aciklama");

        txtAciklama.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout sicilEkleLayout = new javax.swing.GroupLayout(sicilEkle);
        sicilEkle.setLayout(sicilEkleLayout);
        sicilEkleLayout.setHorizontalGroup(
            sicilEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sicilEkleLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(sicilEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSicilEkle1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sicilEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sicilEkleLayout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTCNO, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sicilEkleLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sicilEkleLayout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sicilEkleLayout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sicilEkleLayout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtAdres, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sicilEkleLayout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtAciklama, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(620, Short.MAX_VALUE))
        );
        sicilEkleLayout.setVerticalGroup(
            sicilEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sicilEkleLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(sicilEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTCNO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sicilEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sicilEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sicilEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sicilEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sicilEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAciklama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSicilEkle1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tumBorclarPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblTumBorclar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblTumBorclar);

        javax.swing.GroupLayout tumBorclarPaneLayout = new javax.swing.GroupLayout(tumBorclarPane);
        tumBorclarPane.setLayout(tumBorclarPaneLayout);
        tumBorclarPaneLayout.setHorizontalGroup(
            tumBorclarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tumBorclarPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                .addContainerGap())
        );
        tumBorclarPaneLayout.setVerticalGroup(
            tumBorclarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tumBorclarPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
        );

        kullaniciYonetimiPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setText("Ad");

        jLabel8.setText("Yetki");

        jLabel9.setText("Soyad");

        jLabel10.setText("Telefon");

        txtKullaniciAdi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtSifre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtKullaniciAd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtKullaniciSoyad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTelNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSicilEkle2.setText("Ekle");
        btnSicilEkle2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSicilEkle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSicilEkle2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Kullanici Adi");

        jLabel12.setText("Sifre");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yonetici", "Calisan" }));

        javax.swing.GroupLayout kullaniciYonetimiPaneLayout = new javax.swing.GroupLayout(kullaniciYonetimiPane);
        kullaniciYonetimiPane.setLayout(kullaniciYonetimiPaneLayout);
        kullaniciYonetimiPaneLayout.setHorizontalGroup(
            kullaniciYonetimiPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullaniciYonetimiPaneLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(kullaniciYonetimiPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSicilEkle2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kullaniciYonetimiPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(kullaniciYonetimiPaneLayout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(kullaniciYonetimiPaneLayout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(kullaniciYonetimiPaneLayout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtKullaniciAd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(kullaniciYonetimiPaneLayout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtKullaniciSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(kullaniciYonetimiPaneLayout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(kullaniciYonetimiPaneLayout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(616, Short.MAX_VALUE))
        );
        kullaniciYonetimiPaneLayout.setVerticalGroup(
            kullaniciYonetimiPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullaniciYonetimiPaneLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(kullaniciYonetimiPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kullaniciYonetimiPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kullaniciYonetimiPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKullaniciAd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kullaniciYonetimiPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKullaniciSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kullaniciYonetimiPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kullaniciYonetimiPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jComboBox1))
                .addGap(18, 18, 18)
                .addComponent(btnSicilEkle2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sicilEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(195, Short.MAX_VALUE)
                    .addComponent(sicilGosterPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(195, Short.MAX_VALUE)
                    .addComponent(tumBorclarPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(199, Short.MAX_VALUE)
                    .addComponent(kullaniciYonetimiPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sicilEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sicilGosterPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tumBorclarPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(kullaniciYonetimiPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKrediEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKrediEkleActionPerformed

        try {
            String tc = tblSicil.getValueAt(tblSicil.getSelectedRow(), 0).toString();
            System.out.println(tc);

            SicilDao sicilDao = new SicilDao();
            Sicil sicil = new Sicil();
            sicil = sicilDao.sicilGetirTC(tc);

            BorcEkleFrame borcEkleFrame = new BorcEkleFrame(sicil);
            //borcEkleFrame.setTc(tc);
            borcEkleFrame.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Bir Kisi Seciniz");
        }


    }//GEN-LAST:event_btnKrediEkleActionPerformed

    private void btnSicilSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSicilSilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSicilSilActionPerformed

    private void btnSicilDuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSicilDuzenleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSicilDuzenleActionPerformed

    private void btnSicilEkle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSicilEkle1ActionPerformed
        // TODO add your handling code here:

        SicilDao sicilDao = new SicilDao();
        Sicil sicil = new Sicil();

        sicil.setTCNO(txtTCNO.getText());
        sicil.setAd(txtAd.getText());
        sicil.setSoyad(txtSoyad.getText());
        sicil.setTelefon(txtTelefon.getText());
        sicil.setAdres(txtAdres.getText());
        sicil.setAciklama(txtAciklama.getText());

        try {
            sicilDao.sicilEkle(sicil);
            JOptionPane.showMessageDialog(null, "Kisi Eklendi");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "!!!Kisi Eklenemedi!!!!");
        } finally {
            txtTCNO.setText("");
            txtAd.setText("");
            txtSoyad.setText("");
            txtTelefon.setText("");
            txtAdres.setText("");
            txtAciklama.setText("");
        }
    }//GEN-LAST:event_btnSicilEkle1ActionPerformed

    private void btnKullaniciYonetimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullaniciYonetimiActionPerformed

        sicilGosterPane.setVisible(false);
        tumBorclarPane.setVisible(false);
        sicilEkle.setVisible(false);
        kullaniciYonetimiPane.setVisible(true);

    }//GEN-LAST:event_btnKullaniciYonetimiActionPerformed

    private void btnTumBorclarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTumBorclarActionPerformed
        sicilGosterPane.setVisible(false);
        tumBorclarPane.setVisible(true);
        sicilEkle.setVisible(false);
        kullaniciYonetimiPane.setVisible(false);

        List<Borc> borcs;
        
        BorcDao borcDao = new BorcDao();
        SicilDao sicilDao = new SicilDao();
        borcs = borcDao.borcListele();

        String col[] = {"TC", "Ad", "Soyad", "Telefon", "Tarih", "Toplam Borc", "Taksit", "Durum"};

        DefaultTableModel tableModel = new DefaultTableModel(col, 0);

        for (int i = 0; i < borcs.size(); i++) {
            
            Borc borc = borcs.get(i);
            Sicil sicil = sicilDao.sicilGetir(borc.getSicil_id());
            
            String tcno = sicil.getTCNO();
            String ad = sicil.getAd();
            String soyad = sicil.getSoyad();
            String telefon = sicil.getTelefon();
            Date tarih = borc.getTarih();
            int toplamBorc = borc.getToplam_borc();
            int taksit = borc.getTaksit();
            String odendi = borc.getOdendi();
            if (odendi.equals("0")) {
                odendi = "Odenmedi";
            } else {
                odendi = "Odendi";
            }

            Object[] data = {tcno, ad, soyad, telefon, tarih, toplamBorc, taksit, odendi};

            tableModel.addRow(data);
            tblTumBorclar.setModel(tableModel);

        }

    }//GEN-LAST:event_btnTumBorclarActionPerformed

    private void btnSicilEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSicilEkleActionPerformed

        sicilGosterPane.setVisible(false);
        tumBorclarPane.setVisible(false);
        sicilEkle.setVisible(true);
        kullaniciYonetimiPane.setVisible(false);
    }//GEN-LAST:event_btnSicilEkleActionPerformed

    private void btnSicilGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSicilGosterActionPerformed

        sicilGosterPane.setVisible(true);

        SicilDao sicilDao = new SicilDao();
        sicilDao.sicilListele(tblSicil);
    }//GEN-LAST:event_btnSicilGosterActionPerformed

    private void btnSicilEkle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSicilEkle2ActionPerformed
        try {
            KullaniciDao kullaniciDao = new KullaniciDao();
            Kullanici kullanici = new Kullanici();

            kullanici.setKullanici_adi(txtKullaniciAdi.getText());
            kullanici.setSifre(txtSifre.getText());
            kullanici.setKullanici_ad(txtKullaniciAd.getText());
            kullanici.setKullanici_soyad(txtKullaniciSoyad.getText());
            kullanici.setTel_no(txtTelNo.getText());

            if (jComboBox1.getSelectedItem().equals("Yonetici")) {
                kullanici.setYetki_id(1);
            } else {
                kullanici.setYetki_id(2);
            }

            kullaniciDao.kullaniciEkle(kullanici);

            JOptionPane.showMessageDialog(null, "Kullanici Eklendi");
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            txtKullaniciAdi.setText("");
            txtSifre.setText("");
            txtKullaniciAd.setText("");
            txtKullaniciSoyad.setText("");
            txtTelNo.setText("");
        }
    }//GEN-LAST:event_btnSicilEkle2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame mainFrame = new MainFrame();
                mainFrame.setVisible(true);
                mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKrediEkle;
    private javax.swing.JButton btnKullaniciYonetimi;
    private javax.swing.JButton btnSicilDuzenle;
    private javax.swing.JButton btnSicilEkle;
    private javax.swing.JButton btnSicilEkle1;
    private javax.swing.JButton btnSicilEkle2;
    private javax.swing.JButton btnSicilGoster;
    private javax.swing.JButton btnSicilSil;
    private javax.swing.JButton btnTumBorclar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel kullaniciYonetimiPane;
    private javax.swing.JPanel menuPane;
    private javax.swing.JPanel sicilEkle;
    private javax.swing.JPanel sicilGosterPane;
    private javax.swing.JTable tblSicil;
    private javax.swing.JTable tblTumBorclar;
    private javax.swing.JPanel tumBorclarPane;
    private javax.swing.JTextField txtAciklama;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtAdres;
    private javax.swing.JTextField txtKullaniciAd;
    private javax.swing.JTextField txtKullaniciAdi;
    private javax.swing.JTextField txtKullaniciSoyad;
    private javax.swing.JTextField txtSifre;
    private javax.swing.JTextField txtSoyad;
    private javax.swing.JTextField txtTCNO;
    private javax.swing.JTextField txtTelNo;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
